### ISSUE TITLE
Skipping profile: 'inspec-gcp' on unsupported platform: 'mac_os_x/18.6.0'

### ISSUE THREAD

**Issue by rrey** [inspec/inspec-gcp#156]
# Describe the problem

I'm using kitch-terraform and  my test fails with the following output:
```
basic: Verifying
Skipping profile: 'inspec-gcp' on unsupported platform: 'mac_os_x/18.6.0'.

Profile: basic
Version: (not specified)
Target:  local://

  ×  main: /Users/remi.rey/dev/terraform/base-firewall/test/integration/gcp/controls/main.rb:3
     ×  Control Source Code Error /Users/remi.rey/dev/terraform/base-firewall/test/integration/gcp/controls/main.rb:3
     undefined method `google_compute_forwarding_rule' for #<#<Class:0x00007f9ffadcb580>:0x00007f9ffadc8088>


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <gcp-terraform>.  Please see .kitchen/logs/gcp-terraform.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Main problem seems to be from:
```
Skipping profile: 'inspec-gcp' on unsupported platform: 'mac_os_x/18.6.0'.
```

But I have no idea what could be wrong.

Here is my inspec.yml:
```
$ cat test/integration/gcp/inspec.yml
name: basic
depends:
  - name: inspec-gcp
    git: https://github.com/inspec/inspec-gcp.git
    tag: v0.11.0
```

and the .kitchen.yml:
```
cat .kitchen.yml
driver:
  name: terraform
  command_timeout: 1800

provisioner:
  name: terraform

platforms:
  - name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local

suites:
  - name: gcp
```

Is there anything wrong with my setup ?

**Comment by rrey** [comment]
Called inspec a shell verifier and my problem is now fixed.

**Comment by omazin** [comment]
Hi @rrey, ran into the same problem. Could you elaborate on how exactly did you fix the issue?
Here's my .kitchen.yml config:
```yaml
provisioner:
  name: terraform

platforms:
  - name: local

suites:
  - name: minimal
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/minimal/
    verifier:
      name: terraform
      color: true
      systems:
        - name: minimal
          backend: local
    provisioner:
      name: terraform
```

**Comment by rrey** [comment]
Hi @omazin,

Here is the kitchen.yml that I used:

```yaml
driver:
  name: terraform
  command_timeout: 1800
  root_module_directory: ../
  backend_configurations:
    bucket: SOME_BUCKET
    prefix: SOME_PREFIX

provisioner:
  name: terraform

platforms:
  - name: terraform

verifier:
  name: shell
  command: inspec exec integration/gcp/ -t gcp:// --attrs integration/gcp/attributes.yml

suites:
  - name: gcp
```

**Comment by omazin** [comment]
@rrey thanks, I ended up fixing it without the shell verifier by providing an appropriate `backend` as follows:
```yaml
provisioner:
  name: terraform

platforms:
  - name: local

suites:
  - name: minimal
    driver:
      name: terraform
      command_timeout: 1800
      root_module_directory: test/fixtures/minimal
    verifier:
      name: terraform
      color: true
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - minimal
```
