### ISSUE TITLE
Regional Container Cluster Support for Dashboard, PSP, and MasterAuthorizedNetworks

### ISSUE THREAD

**Issue by bgeesaman** [inspec/inspec-gcp#174]
It appears that the following resource methods available in `google_container_cluster` (a zonal cluster) are not also available in `google_container_regional_cluster` (handles both regional or zonal clusters):

* `pod_security_policy_config` 
* `addons_config.kubernetes_dashboard`
* `master_authorized_networks_config`

# Describe the problem
Example: https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_cluster.rb#L53 is not available in https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_regional_cluster.rb#L82

## Possible Solution
Potentially modify the MM code to include those chunks?  Also, consider a method say, here: https://github.com/inspec/inspec-gcp/blob/master/libraries/google_container_regional_cluster.rb#L140 like:

```
def item
  @fetched
end
```

So that no matter what, access to "everything" can always be reachable with:
```
its('item.pod_security_policy_config.enabled') { should cmp true }
```
even if there is no specific helper for it.

Thanks!

**Comment by bgeesaman** [comment]
As I think was mentioned before, these fields would likely require using the `v1beta1` API endpoint.

**Comment by bgeesaman** [comment]
Also add `binary_authorization` to the list:
```
addonsConfig:
  horizontalPodAutoscaling: {}
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig: {}
binaryAuthorization:
  enabled: true
clusterIpv4Cidr: 10.1.0.0/16
currentMasterVersion: 1.13.7-gke.25
currentNodeVersion: 1.13.7-gke.25
```
