### ISSUE TITLE
Cannot load such file -- google/apis/dns_v2beta1

### ISSUE THREAD

**Issue by abdrehma** [inspec/inspec-gcp#281]
Getting error: 
Failed to complete #verify action: [cannot load such file -- google/apis/dns_v2beta1] on default-terraform

Possible cause:
https://github.com/inspec/inspec-gcp/blob/master/generate/libraries/google_dns_managed_zones.rb#L4

Needing updating to dns_v1beta2 ? 
Source: https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis

Gemfile:

```
source "https://rubygems.org/" do
  gem "kitchen-terraform", "~> 5.5.0"
  gem "inspec", "~> 4.23.10"
end
```

. kitchen.yml:

```
---
    driver:
      name: terraform
      command_timeout: 600
    
    provisioner:
      name: terraform
    
    verifier:
      name: terraform
      fail_fast: false  
    
    platforms:
      - name: terraform
    
    suites:
      - name: default
        driver:
          root_module_directory: test/fixtures/default
        verifier:
          color: true
          systems:
            - name: default
              backend: gcp
 ```

Log:
[kitchen.log](https://github.com/inspec/inspec-gcp/files/5283751/kitchen.log)
