### ISSUE TITLE
verifying via kitchen-terraform verifier

### ISSUE THREAD

**Issue by wyardley** [inspec/inspec-gcp#71]
Are there any examples of using the verifier with `kitchen verify`? Is there any clean way to do this vs. using `inspec exec -t gcp:// [test]`?

I threw up an issue here, but just wondering if anyone here has any context or examples on whether (and how) this is possible.
https://github.com/newcontext-oss/kitchen-terraform/issues/286

**Comment by skpaterson** [comment]
Hi @wyardley, I believe this is a future enhancement, see:
https://github.com/inspec/kitchen-inspec/issues/179
Feel free to comment or 👍 on there!

**Comment by adrienthebo** [comment]
@wyardley a colleague provided this `.kitchen.yml` file; I haven't verified it might it might be worth trying out:

```yml
driver:
  name: terraform

provisioner:
  name: terraform

verifier: # https://www.rubydoc.info/github/newcontext-oss/kitchen-terraform/Kitchen/Verifier/Terraform
  name: terraform
  systems:
    - name: system
      backend: gcp
      shell: true

platforms:
  - name: k8s

suites:
  - name: verify
```
